import React, { useState } from 'react';

export default function ReportExport() {
  const [status, setStatus] = useState('idle'); // idle | loading | done | error

  const handleExport = async () => {
    setStatus('loading');
    try {
      // Dynamic imports to keep the main bundle lean
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
      ]);

      const element = document.getElementById('provenance-results');
      if (!element) throw new Error('Results element not found');

      // Capture with html2canvas
      const canvas = await html2canvas(element, {
        backgroundColor: '#0A0E1A',
        scale: 1.5,
        useCORS: true,
        logging: false,
        windowWidth: element.scrollWidth,
        windowHeight: element.scrollHeight,
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;

      // A4 page dimensions in pt (595.28 × 841.89)
      const pdf = new jsPDF({
        orientation: imgWidth > imgHeight ? 'landscape' : 'portrait',
        unit: 'pt',
        format: 'a4',
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Calculate scaled dimensions to fit page width
      const scale = pageWidth / imgWidth;
      const scaledHeight = imgHeight * scale;

      // Add cover metadata
      pdf.setFillColor(10, 14, 26);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');

      pdf.setTextColor(0, 212, 255);
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Code Provenance Report', 40, 50);

      pdf.setTextColor(107, 122, 153);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Generated: ${new Date().toLocaleString()}`, 40, 68);
      pdf.text('Agent Trust Platform · Artifact Assurance', 40, 82);

      // Horizontal rule
      pdf.setDrawColor(31, 41, 55);
      pdf.setLineWidth(0.5);
      pdf.line(40, 90, pageWidth - 40, 90);

      const contentTop = 100;
      const availableHeight = pageHeight - contentTop - 40;

      if (scaledHeight <= availableHeight) {
        // Single page
        pdf.addImage(imgData, 'PNG', 0, contentTop, pageWidth, scaledHeight);
      } else {
        // Multi-page: slice the canvas into page-sized chunks
        const sliceHeight = Math.floor((availableHeight / scale));
        let yOffset = 0;
        let isFirst = true;

        while (yOffset < imgHeight) {
          if (!isFirst) {
            pdf.addPage();
            pdf.setFillColor(10, 14, 26);
            pdf.rect(0, 0, pageWidth, pageHeight, 'F');
          }

          const sliceCanvas = document.createElement('canvas');
          const remaining = imgHeight - yOffset;
          const thisSlice = Math.min(sliceHeight, remaining);
          sliceCanvas.width = imgWidth;
          sliceCanvas.height = thisSlice;
          const ctx = sliceCanvas.getContext('2d');
          ctx.drawImage(canvas, 0, yOffset, imgWidth, thisSlice, 0, 0, imgWidth, thisSlice);

          const sliceData = sliceCanvas.toDataURL('image/png');
          const startY = isFirst ? contentTop : 20;
          pdf.addImage(sliceData, 'PNG', 0, startY, pageWidth, thisSlice * scale);

          yOffset += thisSlice;
          isFirst = false;
        }
      }

      // Footer on last page
      pdf.setTextColor(31, 41, 55);
      pdf.setFontSize(8);
      pdf.text(
        'Generated by Agent Trust Platform · Artifact Assurance',
        pageWidth / 2,
        pageHeight - 16,
        { align: 'center' }
      );

      pdf.save(`code-provenance-report-${Date.now()}.pdf`);
      setStatus('done');
      setTimeout(() => setStatus('idle'), 3000);
    } catch (err) {
      console.error('PDF export failed:', err);
      setStatus('error');
      setTimeout(() => setStatus('idle'), 3000);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={status === 'loading'}
      className={[
        'flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium transition-all border',
        status === 'loading'
          ? 'bg-surface border-border text-muted cursor-not-allowed'
          : status === 'done'
          ? 'bg-success/10 border-success/30 text-success'
          : status === 'error'
          ? 'bg-danger/10 border-danger/30 text-danger'
          : 'bg-surface border-border text-white hover:border-accent/40 hover:text-accent',
      ].join(' ')}
      title="Export full provenance report as PDF"
    >
      {status === 'loading' ? (
        <>
          <SpinnerIcon />
          Generating PDF…
        </>
      ) : status === 'done' ? (
        <>
          <span>✓</span>
          PDF Saved
        </>
      ) : status === 'error' ? (
        <>
          <span>✕</span>
          Export Failed
        </>
      ) : (
        <>
          <PDFIcon />
          Export PDF Report
        </>
      )}
    </button>
  );
}

function PDFIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
      <path d="M8 1H3a1 1 0 00-1 1v10a1 1 0 001 1h8a1 1 0 001-1V6L8 1z" />
      <path d="M8 1v5h5" />
      <path d="M5 9h4M5 11h2" />
    </svg>
  );
}

function SpinnerIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 14 14"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      className="animate-spin"
    >
      <path d="M7 1.5A5.5 5.5 0 1112.5 7" />
    </svg>
  );
}
