"""
provenance_detector.py
Heuristic-based AI code provenance detector.
Analyzes stylistic markers to determine likely AI model origin.
No external API calls — pure pattern matching.
"""

import re
from typing import Dict, List, Any


# ---------------------------------------------------------------------------
# Pattern definitions
# ---------------------------------------------------------------------------

CLAUDE_PATTERNS: List[Dict[str, Any]] = [
    {
        "name": "Triple-quoted docstring with Args/Returns sections",
        "pattern": r'"""[\s\S]*?(?:Args|Arguments)\s*:\s*[\s\S]*?(?:Returns|Return)\s*:[\s\S]*?"""',
        "weight": 20,
    },
    {
        "name": "Type hints on function signatures",
        "pattern": r'def\s+\w+\s*\([^)]*:\s*\w[\w\[\], |]*[^)]*\)\s*->\s*[\w\[\], |]+\s*:',
        "weight": 15,
    },
    {
        "name": "\"I'll\" in comments (first-person AI voice)",
        "pattern": r"#.*\bI'll\b",
        "weight": 18,
    },
    {
        "name": "Oxford comma in comments",
        "pattern": r"#.*\w+,\s+\w+,\s+and\s+\w+",
        "weight": 10,
    },
    {
        "name": "Structured try/except with specific exceptions and re-raise",
        "pattern": r"except\s+\w+(?:Error|Exception)\s+as\s+\w+\s*:\s*\n\s+(?:logger\.|logging\.|raise\s+\w+)?",
        "weight": 12,
    },
    {
        "name": "Comprehensive module-level docstring",
        "pattern": r'^"""[\s\S]{100,}"""',
        "weight": 10,
    },
    {
        "name": "Raises section in docstring",
        "pattern": r'"""[\s\S]*?Raises\s*:[\s\S]*?"""',
        "weight": 8,
    },
    {
        "name": "Example section in docstring",
        "pattern": r'"""[\s\S]*?Example\s*(?:s)?\s*:[\s\S]*?"""',
        "weight": 7,
    },
]

GPT4_PATTERNS: List[Dict[str, Any]] = [
    {
        "name": "Note: prefixed comment",
        "pattern": r"#\s*Note\s*:",
        "weight": 20,
    },
    {
        "name": "Numbered comment steps",
        "pattern": r"#\s*\d+\.\s+[A-Z]",
        "weight": 18,
    },
    {
        "name": "TODO: consider comment",
        "pattern": r"#\s*TODO[:\s]+consider\b",
        "weight": 22,
    },
    {
        "name": "camelCase mixed with snake_case identifiers",
        "pattern": r"\b[a-z]+[A-Z][a-zA-Z]*\b.*\b[a-z]+_[a-z]+\b",
        "weight": 12,
    },
    {
        "name": "Step-by-step comment block",
        "pattern": r"(?:#\s*Step\s+\d+|#\s*\d\.\s+\w)[\s\S]{0,200}(?:#\s*Step\s+\d+|#\s*\d\.\s+\w)",
        "weight": 15,
    },
    {
        "name": "Helper function pattern with clear naming",
        "pattern": r"def\s+(?:get|set|create|update|delete|check|validate|process|handle)_\w+\(",
        "weight": 8,
    },
    {
        "name": "Explicit None checks with is None / is not None",
        "pattern": r"\bis\s+(?:not\s+)?None\b",
        "weight": 5,
    },
]

GEMINI_PATTERNS: List[Dict[str, Any]] = [
    {
        "name": "Heavy use of list comprehensions",
        "pattern": r"\[.+\s+for\s+\w+\s+in\s+.+(?:\s+if\s+.+)?\]",
        "weight": 15,
    },
    {
        "name": "Minimal or absent docstrings",
        "pattern": r'def\s+\w+\([^)]*\)\s*(?:->\s*\w[\w\[\], |]*)?\s*:\s*\n\s+[^"\s]',
        "weight": 12,
    },
    {
        "name": "Brief single-letter or two-letter variable names",
        "pattern": r"\b(?:x|y|z|i|j|k|n|m|v|s|d|f|g|h|p|q|r|t|u|w)\s*=\s*[^=]",
        "weight": 10,
    },
    {
        "name": "Functional style: map/filter/reduce usage",
        "pattern": r"\b(?:map|filter|reduce)\s*\(",
        "weight": 14,
    },
    {
        "name": "Lambda expressions",
        "pattern": r"\blambda\s+\w[\w,\s]*:",
        "weight": 10,
    },
    {
        "name": "Chained method calls",
        "pattern": r"\.\w+\([^)]*\)\.\w+\([^)]*\)\.\w+\(",
        "weight": 12,
    },
    {
        "name": "Dictionary/set comprehensions",
        "pattern": r"\{.+\s+for\s+\w+\s+in\s+.+\}",
        "weight": 10,
    },
    {
        "name": "Generator expressions",
        "pattern": r"\(.+\s+for\s+\w+\s+in\s+.+\)",
        "weight": 8,
    },
]

COPILOT_PATTERNS: List[Dict[str, Any]] = [
    {
        "name": "# Initialize comment before variable assignment",
        "pattern": r"#\s*[Ii]nitializ\w+\b",
        "weight": 18,
    },
    {
        "name": "Inline comment matching variable name",
        "pattern": r"(\w+)\s*=\s*.+#\s*(?:the\s+)?\1\b",
        "weight": 20,
    },
    {
        "name": "Repetitive similar code blocks",
        "pattern": r"((?:if|elif)\s+\w+\s*[=!<>]+\s*\w+\s*:\s*\n\s+\w+\s*=\s*.+\n){3,}",
        "weight": 18,
    },
    {
        "name": "Boilerplate main guard",
        "pattern": r'if\s+__name__\s*==\s*[\'"]__main__[\'"]\s*:',
        "weight": 8,
    },
    {
        "name": "Autogenerated-style comment above function",
        "pattern": r"#\s*(?:Function|Method|Helper|Utility)\s+to\s+\w+",
        "weight": 15,
    },
    {
        "name": "Repetitive print/log statements",
        "pattern": r"(?:print|logger\.(?:info|debug|warning))\(.*\)\s*\n(?:\s*\w.*\n){0,5}\s*(?:print|logger\.(?:info|debug|warning))\(.*\)",
        "weight": 10,
    },
    {
        "name": "# Check if pattern before conditionals",
        "pattern": r"#\s*[Cc]heck\s+(?:if|whether|for)\b",
        "weight": 12,
    },
]

HUMAN_PATTERNS: List[Dict[str, Any]] = [
    {
        "name": "Inconsistent indentation style",
        "pattern": r"(?:\t    |    \t)",
        "weight": 20,
    },
    {
        "name": "Abbreviated variable names",
        "pattern": r"\b(?:tmp|temp|cnt|idx|num|val|var|obj|arr|lst|dct|buf|msg|res|req|err|exc|cfg|conf|env|ctx|mgr|svc|hdlr|proc|util)\s*=",
        "weight": 14,
    },
    {
        "name": "Sparse or missing comments in non-trivial functions",
        "pattern": r"def\s+\w{5,}\([^)]{10,}\)[^:]*:\s*\n(?:\s+[^\n#\"\']{30,}\n){5,}",
        "weight": 12,
    },
    {
        "name": "Mixed naming conventions in same file",
        "pattern": r"(?:def\s+[a-z]+[A-Z]\w*\(|def\s+[a-z]+_[a-z]+\()[\s\S]{0,500}(?:def\s+[a-z]+[A-Z]\w*\(|def\s+[a-z]+_[a-z]+\()",
        "weight": 15,
    },
    {
        "name": "Commented-out code blocks",
        "pattern": r"#\s*(?:print|return|if|for|while|def|class|import)\b",
        "weight": 16,
    },
    {
        "name": "Magic numbers without explanation",
        "pattern": r"(?:==|!=|<=|>=|<|>|\*|/|\+|-)\s*(?:[2-9]\d{1,3}|[1-9]\d{4,})\b(?!\s*#)",
        "weight": 10,
    },
    {
        "name": "FIXME / HACK / XXX comments",
        "pattern": r"#\s*(?:FIXME|HACK|XXX|WTF|KLUDGE|WORKAROUND)\b",
        "weight": 18,
    },
]

ALL_MODELS = {
    "Claude": CLAUDE_PATTERNS,
    "GPT-4": GPT4_PATTERNS,
    "Gemini": GEMINI_PATTERNS,
    "Copilot": COPILOT_PATTERNS,
    "Human": HUMAN_PATTERNS,
}


# ---------------------------------------------------------------------------
# Scoring helpers
# ---------------------------------------------------------------------------

def _score_patterns(code: str, patterns: List[Dict[str, Any]]) -> tuple[int, List[Dict[str, Any]]]:
    """
    Score a code snippet against a list of patterns.

    Args:
        code: Source code string to analyze.
        patterns: List of pattern dicts with 'pattern', 'name', and 'weight' keys.

    Returns:
        Tuple of (raw_score, matched_markers) where raw_score is the sum of
        weights for matched patterns, and matched_markers is a list of dicts
        with 'marker' and 'weight' keys.
    """
    raw_score = 0
    matched: List[Dict[str, Any]] = []

    for pat in patterns:
        try:
            if re.search(pat["pattern"], code, re.MULTILINE):
                raw_score += pat["weight"]
                matched.append({"marker": pat["name"], "weight": pat["weight"]})
        except re.error:
            # Skip malformed patterns rather than crashing
            continue

    return raw_score, matched


def _normalize_scores(raw_scores: Dict[str, int]) -> Dict[str, int]:
    """
    Normalize raw pattern scores to 0-100 per model using min-max scaling
    relative to the maximum possible score for each model.

    Args:
        raw_scores: Dict mapping model name to raw accumulated score.

    Returns:
        Dict mapping model name to normalized score (0-100).
    """
    max_possible = {
        model_name: sum(p["weight"] for p in patterns)
        for model_name, patterns in ALL_MODELS.items()
    }

    normalized: Dict[str, int] = {}
    for model_name, raw in raw_scores.items():
        max_val = max_possible.get(model_name, 1)
        normalized[model_name] = min(100, int((raw / max_val) * 100))

    return normalized


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def detect_provenance(code: str, language: str) -> dict:
    """
    Analyze stylistic markers in source code to determine likely AI model origin.

    Args:
        code: The source code string to analyze.
        language: Programming language of the code (informational, not currently
                  used for language-specific patterns but reserved for future use).

    Returns:
        A dict with keys:
          - likely_model (str): Name of the most probable model.
          - confidence (int): 0-100 confidence score.
          - markers (list): Matched markers with name and weight.
          - model_scores (dict): Per-model normalized scores (0-100).
    """
    if not code or not code.strip():
        return {
            "likely_model": "Unknown",
            "confidence": 0,
            "markers": [],
            "model_scores": {m: 0 for m in ALL_MODELS},
        }

    raw_scores: Dict[str, int] = {}
    all_markers: Dict[str, List[Dict[str, Any]]] = {}

    for model_name, patterns in ALL_MODELS.items():
        raw, markers = _score_patterns(code, patterns)
        raw_scores[model_name] = raw
        all_markers[model_name] = markers

    normalized = _normalize_scores(raw_scores)

    # Determine winner
    best_model = max(normalized, key=lambda m: normalized[m])
    best_score = normalized[best_model]

    # Confidence: difference between top and second-best score
    sorted_scores = sorted(normalized.values(), reverse=True)
    if len(sorted_scores) >= 2 and sorted_scores[0] > 0:
        gap = sorted_scores[0] - sorted_scores[1]
        # Confidence is the normalized score scaled by the gap ratio
        confidence = min(100, int(best_score * 0.6 + gap * 0.4))
    else:
        confidence = best_score

    # If all scores are zero, mark as Unknown
    if best_score == 0:
        best_model = "Unknown"
        confidence = 0

    # Collect markers for the winning model
    winning_markers = all_markers.get(best_model, [])

    return {
        "likely_model": best_model,
        "confidence": confidence,
        "markers": winning_markers,
        "model_scores": normalized,
    }
